wood_boeing:
  color: [0.6, 0.6, 0.65, 0.01]
  initial_uncertainties: [0.01, 0.01, 0.01, 0.0001, 0.0001, 0.0001]
  localization_object: wood_boeing
  # localization_object_cad: package://custom_ray_trace/sdf/wood_boeing.stl
  # localization_object_filepath: ($find custom_ray_trace)/sdf/wood_boeing.stl 
  prior_offset: [0, 0.0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

goal_hole:
  color: [0, 1, 0, 0.7]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: goal_hole
  # localization_object_cad: package://custom_ray_trace/sdf/goal_hole.stl
  # localization_object_filepath: package://custom_ray_trace/sdf/goal_hole.stl 
  true_frame: [0, 0, 0, 0, 0, 0]
  prior_offset: [0.02, 0.023, 0.025, 0, 0.04, 0.03]
  particle_frame: [0,0,0,0,0,0]

right_datum:
  color: [0, 0, 1, 0.2]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: right_datum
  # localization_object_cad: package://custom_ray_trace/sdf/right_datum.stl
  # localization_object_filepath: package://custom_ray_trace/sdf/right_datum.stl # 
  prior_offset: [0.02, 0, 0, 0, 0.005, 0.01]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

top_datum:
  color: [0.5, 0.5, 0, 0.2]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: top_datum
  # localization_object_cad: package://custom_ray_trace/sdf/top_datum.stl
  # localization_object_filepath: package://custom_ray_trace/sdf/top_datum.stl 
  prior_offset: [0, 0, 0.025, 0, 0.04, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

J1_section:
  color: [ 0.5, 0.5, 0.5, 0.1]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: J1_section
  prior_offset: [0.01, 0.005, -0.003, 0.01, 0, -0.01]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

bottom_section:
  color: [ 0.5, 0.5, 0.5, 0.1]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: bottom_section
  prior_offset: [0, 0, 0.005, -0.01, 0.01, 0]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

back_datum:
  color: [ 0.5, 0.5, 0.5, 0.1]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: back_datum
  prior_offset: [0, 0.023, 0, 0, 0, 0.03]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]



  

