wood_boeing:
  color: [0.6, 0.6, 0.65, 0.01]
  initial_uncertainties: [0.01, 0.01, 0.01, 0.0001, 0.0001, 0.0001]
  localization_object: wood_boeing
  prior_offset: [0, 0.0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

goal_hole:
  color: [0, 1, 0, 0.7]
  initial_uncertainties: [0.06, 0.05, 0.05, 0.04, 0.04, 0.04]
  localization_object: goal_hole
  true_frame: [0, 0, 0, 0, 0, 0]
  prior_offset: [0.02, 0.023, 0.025, 0.005, 0.04, 0.03]
  particle_frame: [0,0,0,0,0,0]

right_datum:
  color: [0, 0, 1, 0.2]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: right_datum
  prior_offset: [0.015, 0.02, 0.015, 0.03, 0.005, 0.01]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

top_datum:
  color: [0.5, 0.5, 0, 0.2]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: top_datum
  prior_offset: [0.025, 0.018, 0.025, 0.03, 0.04, 0.01]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

J1_section:
  color: [ 0.5, 0.5, 0.5, 0.1]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: J1_section
  prior_offset: [0.01, 0.005, -0.003, 0.01, 0, -0.01]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

bottom_section:
  color: [ 0.5, 0.5, 0.5, 0.1]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: bottom_section
  prior_offset: [0.025, 0.018, 0.025, 0.03, 0.04, 0.01]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]

back_datum:
  color: [ 0.5, 0.5, 0.5, 0.1]
  initial_uncertainties: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
  localization_object: back_datum
  prior_offset: [0.012, 0.023, 0.015, 0.03, 0.05, 0.03]
  true_frame: [0, 0, 0, 0, 0, 0]
  particle_frame: [0,0,0,0,0,0]



  

